name = "ExportAll"
uuid = "ad2082ca-a69e-11e9-38fa-e96309a31fe4"
authors = ["John Tinnerholm johti <johti17@liu.se>"]
version = "0.1.2"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
[compat]
julia = "1.1"
